### PR TITLE
fix(flex): fix flex error with maxHeight

### LINKED ISSUE #30: overflow:scroll,if set maxWidth/maxHeight node size is error
### Affected version

0.12.0 and main

### No same issues found.

- [X] Yes, I search all issues but not found.

### Steps to Reproduce

look code

### Code example

    let box = document.createElement('div');
    document.body.style.background= '#f92';
    document.body.style.width= '300px';
    document.body.style.height= '300px';
    document.body.style.display= 'flex';
    document.body.style.flexDirection= 'column';
    document.body.appendChild(box);

    box.style.background = '#6ad0e2';
    box.style.display = 'flex';
    box.style.flexDirection='column';

    const icon = document.createElement('div');
    icon.style.zIndex = 0;
    icon.style.background= '#f32';
    icon.style.maxHeight = '30px';
    icon.style.flexGrow = 1;
    icon.style.display = 'flex';
    icon.style.overflow = 'scroll';
    icon.style.fexShrink = 1

    box.appendChild(icon);

### Expected results

截屏2022-08-19 18 17 57

### Actual results

截屏2022-08-19 18 19 08

### PR DESCRIPTION
**Pull request by pba-cra**
fix #30

### CODE REVIEW

File: webf/lib/src/rendering/box_model.dart [hunk 1]
```diff
@@ -884,6 +884,14 @@ class RenderBoxModel extends RenderBox
             : 0,
         maxHeight: double.infinity,
       );
+      if(parent is RenderFlexLayout) {
```
Comment (andycall) [inline webf/lib/src/rendering/box_model.dart:887]: code style

**Review by devjiangzhou — APPROVED** [review]

**Review by andycall — APPROVED** [review]
